version: 2
before:
  hooks:
    - rustup default stable
    - cargo install --locked cargo-zigbuild
    - cargo fetch --locked
builds:
  - builder: rust
    flags:
      - --release
    targets:
      - x86_64-unknown-linux-musl
      - aarch64-unknown-linux-musl
archives:
  - formats: [binary]
    name_template: "{{ .ProjectName }}_{{- title .Os }}_{{ .Arch }}"
