name: github-actions-cache
runs:
  using: "composite"
  steps:
    - name: Start Github Actions Cache
      shell: bash
      run: |
        OUT_PATH=$(nix build --no-link --print-out-paths "$GITHUB_ACTION_PATH")
        "$OUT_PATH"/bin/github-actions-cache &
