name: github-actions-cache
inputs:
  repo:
    description: "repo to use for binary"
    required: true
    default: NickCao/github-actions-cache
runs:
  using: "composite"
  steps:
    - name: Export Env
      uses: NickCao/actions-export-envs@main
      id: envs
    - name: Start Github Actions Cache
      shell: bash
      run: |
        curl -o /tmp/github-actions-cache \
          https://github.com/${{ inputs.repo }}/releases/latest/download/github-actions-cache_$(go env GOOS)_$(go env GOARCH)
        chmod +x /tmp/github-actions-cache
        /tmp/github-actions-cache &
      env:
        ACTIONS_RUNTIME_TOKEN: ${{ steps.envs.outputs.ACTIONS_RUNTIME_TOKEN }}
        ACTIONS_RESULTS_URL: ${{ steps.envs.outputs.ACTIONS_RESULTS_URL }}
