name: release
on: [ push ]
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - uses: cargo-bins/cargo-binstall@main
    - name: build
      run: |
        cargo-binstall -y cross
        cross build --release --target-dir  x86_64-target --target  x86_64-unknown-linux-musl
        cross build --release --target-dir aarch64-target --target aarch64-unknown-linux-musl
    - name: release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.sha }}
        target_commitish: ${{ github.sha }}
        files: |
          *-target/*/release/github-actions-cache
