name: selftest
on:
  - push
jobs:
  selftest:
    strategy:
      matrix:
        runs-on:
          - ubuntu-24.04
          - ubuntu-24.04-arm
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - uses: ./
      - name: selftest
        run: |
          nix copy --extra-substituters http://127.0.0.1:3000 --to http://127.0.0.1:3000
